sudo: required
dist: trusty
language: python
python:
- '2.7'
branches:
  only:
  - master
addons:
  apt:
    packages:
    - language-pack-en
    - language-pack-th
install:
- pip install -r requirements.txt
- make download
script:
- make publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
